navigation:
- text: Home
  url: /
- text: Contact Me
  url: /contact.html
- text: Portfolio
  url: /portfolio.html
- text: Blog
  url: /blog/
- text: Resume
  url: /resume.html
- text: Toys
  url: /toys/

permalink: /blog/:year/:month/:day/:title
pygments: true
